import type { CompareData, Finding, HomeData, SessionDetail, SessionSummary, SourceState } from "./types";

const sessions: SessionSummary[] = [
  { id:"a", name:"修复支付页面加载慢的问题", project:"storefront", source:"Codex", model:"gpt-5.1", startedAt:"2026-07-19T10:21:00Z", durationSec:163, cost:.042, tokens:18420, health:92, status:"smooth", toolFailures:0, loopCost:0, capability:"detailed" },
  { id:"b", name:"修复 WebSocket 重连", project:"api-gateway", source:"Claude Code", model:"claude-sonnet-4", startedAt:"2026-07-19T09:47:00Z", durationSec:310, cost:.052, tokens:24120, health:64, status:"attention", toolFailures:2, loopCost:.013, capability:"detailed" },
  { id:"c", name:"审查迁移方案", project:"agenttrace", source:"Gemini", model:"gemini-2.5-pro", startedAt:"2026-07-18T16:10:00Z", durationSec:92, cost:.018, tokens:8300, health:86, status:"smooth", toolFailures:0, loopCost:0, capability:"detailed" },
  { id:"d", name:"更新库存搜索", project:"inventory", source:"Hermes", model:"gpt-5-mini", startedAt:"2026-07-18T14:32:00Z", durationSec:221, cost:.034, tokens:12700, health:78, status:"attention", toolFailures:1, loopCost:.006, capability:"aggregate" },
  { id:"e", name:"补充接口测试", project:"api-gateway", source:"Codex", model:"gpt-5.1", startedAt:"2026-07-18T12:10:00Z", durationSec:74, cost:.014, tokens:7200, health:90, status:"smooth", toolFailures:0, loopCost:0, capability:"detailed" },
  { id:"f", name:"整理发布说明", project:"agenttrace", source:"Claude Code", model:"claude-sonnet-4", startedAt:"2026-07-18T11:32:00Z", durationSec:142, cost:.024, tokens:9300, health:88, status:"smooth", toolFailures:0, loopCost:0, capability:"detailed" },
];
const findings: Finding[] = [
  { id:"b-loop", sessionId:"b", sessionName:sessions[1].name, kind:"loop", value:.13, detail:"", severity:"high", evidence:[{kind:"repeated_groups",value:"3"}] },
  { id:"b-retry", sessionId:"b", sessionName:sessions[1].name, kind:"retry", value:2, detail:"", severity:"medium", evidence:[{kind:"failed_calls",value:"2"}] },
  { id:"d-context", sessionId:"d", sessionName:sessions[3].name, kind:"context", value:76, detail:"", severity:"medium", evidence:[{kind:"context_used",value:"76%"}] },
];
const sourceState: SourceState = { localOnly:true, sessionCount:sessions.length, sources:[{name:"Claude Code",detected:true},{name:"Codex CLI",detected:true},{name:"Gemini CLI",detected:true},{name:"Hermes Agent",detected:true}] };
const home: HomeData = { totalSessions:12424, smoothSessions:10685, totalCost:.48, potentialSavings:.09, averageHealth:86, attention:findings.map(({sessionId,kind,value,detail,severity})=>({sessionId,kind,value,detail,severity})), recentSessions:sessions, dataHealth:{discovered:6,parsed:6,skipped:0,cache_hits:0,unknown_sources:0,unknown_models:0,fallback_pricing:0,latest_session_at:sessions[0].startedAt,confidence:"high",with_tokens:6,with_duration:6,with_tools:6,with_event_timing:5,with_diagnostics:5} };
function detail(id:string): SessionDetail { const session=sessions.find(item=>item.id===id)??sessions[0]; return { session, anomalies:[], warnings:[], findings:findings.filter(item=>item.sessionId===session.id), contextUtilization:session.id==="d"?76:42, maxToolLatencySec:session.id==="b"?18.2:1.4, steps:[] }; }
function compare(id:string, previousId?:string): CompareData { const current=sessions.find(item=>item.id===id)??sessions[0]; const previous=sessions.find(item=>item.id===previousId)??(current.id==="a"?sessions[1]:sessions[0]); const faster=current.durationSec<=previous.durationSec, cheaper=current.cost<=previous.cost; return { current, previous, outcome:faster?(cheaper?"faster_cheaper":"faster_costlier"):(cheaper?"slower_cheaper":"slower_costlier"), reasons:["fewer_failures","less_repeated_work"], metrics:[{kind:"duration",current:current.durationSec,previous:previous.durationSec,unit:"sec",lowerIsBetter:true},{kind:"cost",current:current.cost,previous:previous.cost,unit:"usd",lowerIsBetter:true},{kind:"tool_failures",current:current.toolFailures,previous:previous.toolFailures,unit:"count",lowerIsBetter:true},{kind:"repeated_work",current:current.loopCost,previous:previous.loopCost,unit:"usd",lowerIsBetter:true}] }; }
export const mockApi = { refreshSessions:async()=>{}, detectSources:async()=>sourceState, loadHome:async()=>home, listSessions:async()=>({sessions,total:sessions.length}), getSession:async(id:string)=>detail(id), listFindings:async()=>findings, compareSessions:async(id:string,previousId?:string)=>compare(id,previousId) };
